export const CLEAR_NETWORK_STATS = 'CLEAR_NETWORK_STATS';
export const REDIRECT_TO = 'REDIRECT_TO';
export const GET_ERROR_STATUS_CODE = 'GET_ERROR_STATUS_CODE';
export const GET_ERRORS = "GET_ERRORS";