export const GET_INDEX_DATA = "GET_INDEX_DATA";
export const INDEX_LOADING_STARTS = "INDEX_LOADING_STARTS";
export const INDEX_LOADING_ENDS = "INDEX_LOADING_ENDS";
export const GET_INDEX_ERROR = "GET_INDEX_ERROR";

export const INDEX_EACH_POST_LOADING_STARTS = "INDEX_EACH_POST_LOADING_STARTS";
export const INDEX_EACH_POST_LOADING_ENDS = "INDEX_EACH_POST_LOADING_ENDS";

export const MY_LIKED_POST_LOADING_STARTS = "MY_LIKED_POST_LOADING_STARTS";
export const MY_LIKED_POST_LOADING_ENDS = "MY_LIKED_POST_LOADING_ENDS";
export const GET_MY_LIKED_DATA = "GET_MY_LIKED_DATA"

export const CRUD_OPERATION_STARTS = "CRUD_OPERATION_STARTS";
export const CRUD_OPERATION_ENDS = "CRUD_OPERATION_ENDS";
export const DELETE_USER_POST = "DELETE_USER_POST";