export const GET_INDEX_DATA = "GET_INDEX_DATA";
export const INDEX_LOADING_STARTS = "INDEX_LOADING_STARTS";
export const INDEX_LOADING_ENDS = "INDEX_LOADING_ENDS"
export const GET_INDEX_ERROR = "GET_INDEX_ERROR"