export const LAYOUT_LOADING_STARTS = "LAYOUT_LOADING_STARTS";
export const LAYOUT_LOADING_ENDS = 'LAYOUT_LOADING_ENDS';
export const GET_LAYOUT_DATA = "GET_LAYOUT_DATA";
export const GET_LAYOUT_ERROR = "GET_LAYOUT_ERROR";