export const PROFILE_LOADING_STARTS = "PROFILE_LOADING_STARTS";
export const PROFILE_LOADING_ENDS = "PROFILE_LOADING_ENDS";
export const GET_PROFILE_DATA = "GET_PROFILE_DATA";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";