export const PUBLIC_POST_LOADING_STARTS = "PUBLIC_POST_LOADING_STARTS";
export const PUBLIC_POST_LOADING_ENDS = "PUBLIC_POST_LOADING_ENDS";
export const PUBLIC_POST_GET_DATA = "PUBLIC_POST_GET_DATA";
export const PUBLIC_POST_GET_SINGLE_DATA = "PUBLIC_POST_GET_SINGLE_DATA";
export const PUBLIC_POST_GET_ERROR = "PUBLIC_POST_GET_ERROR";

export const PUBLIC_POST_COMMENTS_LOADING_STARTS = "PUBLIC_POST_COMMENTS_LOADING_STARTS";
export const PUBLIC_POST_COMMENTS_LOADING_ENDS = "PUBLIC_POST_COMMENTS_LOADING_ENDS";
export const GET_PUBLIC_POST_COMMENTS_DATA = "GET_PUBLIC_POST_COMMENTS_DATA";

export const PUBLIC_POST_COMMENT_CRUD_STARTS = "PUBLIC_POST_COMMENT_CRUD_STARTS";
export const PUBLIC_POST_COMMENT_CRUD_ENDS = "PUBLIC_POST_COMMENT_CRUD_ENDS"

export const LIKE_POST_LOADING_STARTS = "LIKE_POST_LOADING_STARTS";
export const LIKE_POST_LOADING_ENDS = "LIKE_POST_LOADING_ENDS";
export const LIKE_POST_DATA = "LIKE_POST_DATA";
export const CHECK_LIKE_DATA = "CHECK_LIKE_DATA" 

export const CRUD_LIKE_LOADING_STARTS = "CRUD_LIKE_LOADING_STARTS";
export const CRUD_LIKE_LOADING_ENDS = "CRUD_LIKE_LOADING_ENDS";

export const FILTER_POST_LOADING_STARTS = "FILTER_POST_LOADING_STARTS";
export const FILTER_POST_LOADING_ENDS = "FILTER_POST_LOADING_ENDS";

export const GET_CITIES_IN_DB = "GET_CITIES_IN_DB";
export const GET_TYPES_IN_DB = "GET_TYPES_IN_DB";

export const RESET_SEARCH_DATA = "RESET_SEARCH_DATA";