export const PUBLIC_POST_LOADING_STARTS = "PUBLIC_POST_LOADING_STARTS";
export const PUBLIC_POST_LOADING_ENDS = "PUBLIC_POST_LOADING_ENDS";
export const PUBLIC_POST_LOADING_DATA = "PUBLIC_POST_LOADING_DATA";