export const PROPERTY_POST_DATA_LOADING_STARTS = "PROPERTY_POST_DATA_LOADING_STARTS";
export const PROPERTY_POST_DATA_LOADING_ENDS = "PROPERTY_POST_DATA_LOADING_ENDS";
export const GET_PROPERTY_DATA = "GET_PROPERTY_DATA";
export const GET_A_PROPERTY_DATA = "GET_A_PROPERTY_DATA";
export const GET_PROPERTY_ERROR = "GET_PROPERTY_ERROR"